import './globals.css';
import { Roboto } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import {ThemeProvider} from '@/context/ThemeContext';
import AuthProvider from '@/components/AuthProvider';

const roboto = Roboto({ subsets: ['latin'], weight: '300' });

export const metadata = {
  title: 'Next BlogPosts',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};
